name: flutter_deep_linking
description: '🧭 Describe your routing declaratively and handle deep links properly!'
version: 0.2.1
homepage: https://github.com/JonasWanke/flutter_deep_linking

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  flutter_test:
    sdk: flutter
  test: ^1.16.0
